import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {ItemCard} from 'components/cards';
import MainPage from 'components/UI/main';
import SearchModal from 'components/UI/searchModal';
import React, { useState, useEffect } from 'react';

export default function Home() {
  const [searchVisible, setSearchVisible] = useState(false);

  const searchClose = () => {
    setSearchVisible(false);
  }

  const today = new Date();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className={styles.header}>
          <span style={{ fontSize: '24px', fontWeight: '700' }} >Anime</span>
          <div className={styles.searchbar}>
            <div className={styles.searchicon} >
              <Image src="/search.svg" width={18} height={18} alt="" />
            </div>
            <input 
              className={styles.searchtext} 
              type="text" 
              placeholder="Search..." 
              onClick={() => {setSearchVisible(true);}}
            />
          </div>
          <span  style={{ fontSize: '14px', color: '#5A5A5A' }} >Today is the {today.toDateString()}</span>
        </div>
      </header>

      <main className={styles.main}>
        <MainPage />
        {searchVisible && <SearchModal onClose={searchClose} />}
      </main>

      <footer className={styles.footer}>
        <div className={styles.footer_cont}>
          <p className={styles.footer_title}>Your Name</p>
          <p className={styles.footer_note}>A few words about how you found Coinable and how did you feel about this task</p>
        </div>
      </footer>
    </div>
  )
}
